// LISTAR
GET http://localhost:5000/usuarios
Content-Type: application/json


{

}

// CADASTRAR/REGISTRAR
###
POST http://localhost:5000/usuarios
Content-Type: application/json

{
  "nome": "",
  "email": "",
  "senha": "",
  "confirmarSenha": "",
  "curso": "",
  "disciplina": "",
  "periodo":  ,
  "tipoUsuario": ""
}

###
PUT http://localhost:5000/usuarios/
Content-Type: application/json


{
  "nome": "",
  "email": "",
  "senha": "",
  "confirmarSenha": "",
  "curso": "",
  "disciplina": "",
  "periodo": ,
  "tipoUsuario": ""
}

// EXCLUIR USUÁRIO
###
DELETE http://localhost:5000/usuarios/


// LOGAR
###
POST http://localhost:5000/usuarios/login
Content-Type: application/json

{
  "email": "",
  "senha": ""
}

// CRIAR PERGUNTAS/POSTS
###
POST http://localhost:5000/usuarios/posts
Content-Type: application/json

{
  "alunoId": "67241d7dca748411e52964d4", 
  "categoria": "Tecnologia",
  "titulo": "Ola, boa noite.",
  "conteudo": "Amanha será feriado"
  
}

// listando os posts
###
GET  http://localhost:5000/usuarios/posts/listar
Content-Type: application/json

{
  
}



// Deletar post
###
DELETE http://localhost:5000/usuarios/posts/6726ee2bfda98f72580b8103
Content-Type: application/json

{

}

// Dar like e ao mesmo tempo remover like do post
###
POST http://localhost:5000/usuarios/posts/67302ee47da6408bac5e5f01/like 
Content-Type: application/json

{
  "userId": "671a63383b8c4cd56090cca6"
}



// Criar comentario
###
POST http://localhost:5000/usuarios/posts/67302ee47da6408bac5e5f01/comentarios
Content-Type: application/json

 
{
  "usuarioId": "67267a28f5451bcf445bac3c",
  "conteudo": "Ainda bem."
}




// Dar like e ao mesmo tempo remover like do comentário
###
POST http://localhost:5000/usuarios/posts/67302ee47da6408bac5e5f01/comentarios/67302f1d7da6408bac5e5f07/like
Content-Type: application/json

{
  "usuarioId": "671a63383b8c4cd56090cca6"
}

